name: Deployment

on:
  push:
    tags: [ '*.*.*' ]
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    name: Build, test and release to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: gradle build -x test

      - name: Test app
        run: gradle test

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ftndevops123/user-service
          tag: ${{ github.ref_name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          cache_registry: aevea/cache
